### ISSUE TITLE
Admin menu blocking left side of image upload pop-up windows. 

### ISSUE THREAD

**Issue by WalterGoedecke** [renyi/mezzanine-themes#28]
![mezzanine_screenshot-left_menu_problem-crop](https://cloud.githubusercontent.com/assets/13490261/10671452/d84f7cd6-78a7-11e5-870e-069fa3dba8eb.png)
I have a problem with an unwanted left side admin menu blocking part of the image upload and link popup windows. 

When an editable rich text page is made, and one wants to add images to upload, the admin menu will block the left side of the popup window, rendering it usless, as one can't see the file they are selecting. I have included a screen-shot file (Mezzanine_screenshot-left_menu_problem-crop.png). I have partially corrected this by modifying the file at "~/lib/python3.4/site-packages/grappelli_safe/templates/admin/base.html" by adding an "if not" block at the bottom, to conditionally block the footer, which is the unwanted admin menu:  

    {% if not results_var.results_current %}
        
        {% block footer %}<div id="footer"></div>{% endblock %}
    {% endif %}

This did work for one website I made, and not block the admin menu for the website for ~/admin/; however, this did not work for another website I made. I do not understand mezzanine, nor django enough to block this unwanted admin menu. 

Would you be able to shed light on this issue? 

Thanks, 
Walter Goedecke

**Comment by sanjivj** [comment]
There is a way around this problem (without reprogramming Mezzanine!):

1) Create  an 'img' file within your app's static file, if you do not have one already.

2) Find images on the internet, your computer, wherever and move them to this img file. If you are working in a Linux environment, download an image with the 'wget' command.

3)Run the collectstatic thing to get the image to the project's static file.

4)At this point, you can install the image in the desired webpage WITHOUT seeing the annoying admin window you were referring to. Just hit the icon to add an image, do NOT hit the 'camera' icon. Next, type in '/static/img/myNiceImage.jpg' in the source box; obviously 'myNiceImage.jpg' would be actually be replaced by the name of your image :). Remember to uncheck the constraints box. This will give you an over-sized image, but you can edit again and make it smaller.

**Comment by WalterGoedecke** [comment]
Thanks, Sanjivj

You're saying that pasting the path to the image file in the selector box will work around the problem. 
I've also found out with more experimenting, that adding the following if block to "block" the footer menu: 
    {% if not query.pop %}
        
        {% block footer %}<div id="footer"></div>{% endblock %}
    {% endif %}
 works for both of my websites, and does not block the admin menu for the admn page. 

Thanks, 
Walter

**Comment by renyi** [comment]
Thanks guys. Closing this, :)
